openapi: 3.0.0
info:
  title: Library-management-api
  description: The API for the Library management project
  version: 1.0.0
servers:
- url: https://virtserver.swaggerhub.com/HEIFEDORA3/LibraryManagementTD/1.0.0
  description: SwaggerHub API Auto Mocking
paths:
  /books:
    get:
      summary: Get the whole books
      description: Retrieves the current book list
      parameters:
      - name: bookName
        in: query
        description: Filter books by name/tittle
        required: false
        style: form
        explode: true
        schema:
          type: string
      - name: releaseDateFrom
        in: query
        description: Start date for filtering books by release date
        required: false
        style: form
        explode: true
        schema:
          type: string
          format: date
      - name: releaseDateTo
        in: query
        description: End date for filtering books by release date
        required: false
        style: form
        explode: true
        schema:
          type: string
          format: date
      responses:
        "200":
          description: "ok, It's a succes"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Book'
    put:
      summary: Update an existing book
      description: this request is idempotent
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Book'
        required: true
      responses:
        "200":
          description: Book update successfully
    post:
      summary: Add new book
      description: create and add new book
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Book'
        required: true
      responses:
        "200":
          description: Book created successfully
    delete:
      summary: Delete book
      description: Delete book by ID
      parameters:
      - name: ID
        in: query
        description: The id of the book to delete
        required: true
        style: form
        explode: true
        schema:
          type: integer
      responses:
        "200":
          description: Book deleted successfully
        "404":
          description: Book not found
  /authors:
    get:
      summary: Get a list of authors
      parameters:
      - name: authorName
        in: query
        description: Filter authors by name
        required: false
        style: form
        explode: true
        schema:
          type: string
      responses:
        "200":
          description: List of authors returned successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Author'
    put:
      summary: Update an existing author
      description: This request is idempotente
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Author'
        required: true
      responses:
        "200":
          description: Author update successfully
    post:
      summary: Create new author
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Author'
        required: true
      responses:
        "200":
          description: New author added
    delete:
      summary: Delete author
      description: Delete author by ID
      parameters:
      - name: ID
        in: query
        description: the id of the author ton delete
        required: true
        style: form
        explode: true
        schema:
          type: integer
      responses:
        "200":
          description: Author deleted successfully
        "404":
          description: Author not found or not exist
components:
  schemas:
    Book:
      required:
      - author
      - bookName
      type: object
      properties:
        ID:
          type: integer
          description: A book unique identifier
        bookName:
          type: string
          description: The title of the book
        author:
          type: string
          description: The guy who write the book
        pageNumber:
          type: integer
          description: Total number of pages
        topic:
          type: string
          description: The genre of the book
          enum:
          - ROMANCE
          - COMEDY
          - OTHER
        releaseDate:
          type: string
          format: date
    Author:
      required:
      - Name
      type: object
      properties:
        ID:
          type: integer
          description: Author's unique identifier
        Name:
          type: string
          description: It can be the author's real name or their pen name
        Sex:
          type: string
          description: Gender of the author
          enum:
          - M
          - F
